const $=s=>document.querySelector(s);
let D=JSON.parse(localStorage.getItem("veroV2")||'{"xp":0,"missions":0,"focus":0,"workouts":0,"steps":0,"books":[],"ach":[],"recent":[],"boredRecent":[]}');
const ranks=["RECRUIT","FIELD AGENT","SPECIAL AGENT","ELITE AGENT","MASTER SPY","DIRECTOR"];
function lvl(){return Math.floor(D.xp/250)+1} function save(){localStorage.setItem("veroV2",JSON.stringify(D));dash()}
function dash(){let L=lvl(),base=(L-1)*250;$("#level").textContent="LEVEL "+L;$("#rank").textContent=ranks[Math.min(ranks.length-1,Math.floor((L-1)/2))];$("#xptext").textContent=(D.xp-base)+" / 250 XP";$("#xpbar").style.width=((D.xp-base)/250*100)+"%";$("#mc").textContent=D.missions;$("#dc").textContent=D.focus;$("#bc").textContent=D.books.length;$("#ac").textContent=D.ach.length;if(L>=5){$("#vault").classList.remove("locked");$("#vault").querySelector("small").textContent="ACCESS GRANTED"}if(L>=10){$("#secret").classList.remove("locked");$("#secret").querySelector("small").textContent="DECRYPTED"}}
function panel(t){let L=lvl();if(t==="vault"&&L<5){play("denied");return alert("CLASSIFIED — Level 5 required.");}if(t==="secret"&&L<10){play("denied");return alert("TOP SECRET — Clearance insufficient.");}play(t==="secret"?"secret":t==="doom"?"lock":"open");$("#overlay").classList.remove("hidden");render(t)}
function closeP(){play("close");$("#overlay").classList.add("hidden")}
function pick(pool,key){let recent=D[key]||[],choices=pool.map((x,i)=>i).filter(i=>!recent.includes(i));if(!choices.length){D[key]=[];choices=pool.map((x,i)=>i)}let i=choices[Math.floor(Math.random()*choices.length)];D[key]=[i,...recent].slice(0,20);save();return pool[i]}
function render(t){let h="";if(t==="doom"){let m=pick(MISSIONS,"recent");window.current=m;h=`<h2>📵 FOCUS PROTOCOL</h2><p>Instagram + Facebook <b>🔒 TARGETS</b></p><div class="mission"><span class="tag">${m.icon} ${m.cat}</span><span class="tag">~${m.mins} MIN</span><span class="tag">+${m.xp} XP</span><h3>🎯 NUEVA MISIÓN</h3>${m.text}</div><button class="btn" onclick="finishMission()">✓ MISIÓN COMPLETADA</button><button class="btn pink" onclick="reroll()">↻ CAMBIAR MISIÓN (1)</button><p class="warn">El bloqueo REAL de Instagram/Facebook se conectará a Android/MacroDroid. Esta interfaz no puede bloquear apps por sí sola.</p>`}
if(t==="progress")h=`<h2>🏋🏻‍♀️ FIELD LOG</h2><div class="log">Entrenamientos: <b>${D.workouts}</b><br>Metas de pasos: <b>${D.steps}</b></div><button class="btn" onclick="log('workouts')">✓ ENTRENÉ HOY +25 XP</button><button class="btn pink" onclick="log('steps')">✓ CUMPLÍ MIS PASOS +15 XP</button>`;
if(t==="bored"){play("transmission");let b=pick(BORED,"boredRecent");h=`<h2>🎲 RANDOM OPS</h2><div class="mission"><span class="tag">${b.icon} ${b.cat}</span><h3>MISIÓN ANTI-ABURRIMIENTO</h3>${b.text}</div><button class="btn pink" onclick="render('bored')">DAME OTRA</button><button class="btn" onclick="boredDone()">✓ LA HICE +10 XP</button>`}
if(t==="library")h=`<h2>📚 INTELLIGENCE ARCHIVES</h2><input class="input" id="bt" placeholder="Libro"><input class="input" id="ba" placeholder="Autor/a"><input class="input" id="bcov" placeholder="URL de portada (opcional)"><textarea class="input" id="br" placeholder="Reseña / pensamientos"></textarea><button class="btn" onclick="addBook()">ARCHIVAR +20 XP</button>${books()}`;
if(t==="vault")h=`<h2>🔓 CLASSIFIED VAULT</h2><div class="mission"><h3>CLEARANCE ACCEPTED</h3>Has desbloqueado el Archivo Clasificado. Aquí vivirán temas visuales, estadísticas avanzadas e insignias especiales.</div><button class="btn pink" onclick="award('VAULT BREAKER','Accediste al archivo clasificado.',75)">RECLAMAR INSIGNIA</button>`;
if(t==="secret")h=`<h2>🕵🏻‍♀️ TOP SECRET</h2><div class="mission"><h3>DECRYPTION COMPLETE</h3>AGENT V: encontraste el módulo secreto. Esta zona queda reservada para futuras funciones sorpresa. ♡</div><button class="btn" onclick="award('THE PINK FILE','Descifraste el expediente rosa.',150)">ARCHIVAR DESCUBRIMIENTO</button>`;$("#content").innerHTML=h}
let changed=false;function reroll(){if(changed){play("denied");return alert("Ya usaste tu cambio, agente.");}play("reroll");changed=true;let m=pick(MISSIONS,"recent");window.current=m;render("doom");changed=true}
function finishMission(){play("complete");let m=window.current||MISSIONS[0];D.missions++;D.focus++;D.xp+=m.xp;changed=false;save();check();alert("✓ Misión archivada. +"+m.xp+" XP");closeP()}
function boredDone(){play("complete");D.missions++;D.xp+=10;save();check();render("bored")}
function log(k){play("archive");let day=new Date().toISOString().slice(0,10),key=k+day;if(localStorage.getItem(key))return alert("Ya lo registraste hoy ♡");localStorage.setItem(key,"1");D[k]++;D.xp+=k==="workouts"?25:15;save();check();render("progress")}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function addBook(){play("archive");let t=$("#bt").value.trim();if(!t)return alert("Falta el nombre del libro ♡");D.books.unshift({t,a:$("#ba").value.trim(),c:$("#bcov").value.trim(),r:$("#br").value.trim()});D.xp+=20;save();check();render("library")}
function books(){return D.books.map((b,i)=>`<div class="book">${b.c?`<img src="${esc(b.c)}" style="width:50px;height:72px;object-fit:cover;float:left;margin-right:10px;border-radius:6px">`:""}<b>${esc(b.t)}</b><br><small>${esc(b.a)}</small><p>${esc(b.r)}</p><button onclick="D.books.splice(${i},1);save();render('library')">Eliminar</button><div style="clear:both"></div></div>`).join("")}
const ACH=[["TOUCH GRASS",()=>D.focus>=10,"10 protocolos anti-doomscroll.",100],["BOOKWORM INTELLIGENCE",()=>D.books.length>=5,"5 libros archivados.",100],["SHE'S ALIVE!",()=>D.steps>=7,"7 metas de pasos.",75],["FIELD TRAINING",()=>D.workouts>=10,"10 entrenamientos.",100],["AGENT OF CHAOS",()=>D.missions>=25,"25 misiones completadas.",125]];
function check(){for(let a of ACH)if(a[1]()&&!D.ach.includes(a[0])){D.ach.push(a[0]);D.xp+=a[3];localStorage.setItem("veroV2",JSON.stringify(D));showAch(a[0],a[2],a[3]);break}}
function showAch(n,d,x){play("achievement");let e=$("#achievement");e.innerHTML=`<small>✦ ACHIEVEMENT UNLOCKED ✦</small><h2>${n}</h2><p>${d}</p><b>+${x} XP</b><br><button class="btn pink" onclick="$('#achievement').classList.add('hidden');dash()">ARCHIVAR PREMIO</button>`;e.classList.remove("hidden")}
function award(n,d,x){if(D.ach.includes(n)){play("denied");return alert("Insignia ya archivada ♡");}play("xp");D.ach.push(n);D.xp+=x;save();showAch(n,d,x)}
dash();